// test main stringutils generated by make-c-tests-main

// Includes
#include "stringutils_c.h"


int main () {

 printf("stringutils.escape_string_test_empty ==> %s\n", stringutils__escape_string_test_empty() ? "true" : "false");

 printf("stringutils.escape_string_test_no_escape ==> %s\n", stringutils__escape_string_test_no_escape() ? "true" : "false");

 printf("stringutils.escape_string_test_quote ==> %s\n", stringutils__escape_string_test_quote() ? "true" : "false");

 printf("stringutils.escape_string_test_backslash ==> %s\n", stringutils__escape_string_test_backslash() ? "true" : "false");

 printf("stringutils.escape_string_test_backspace ==> %s\n", stringutils__escape_string_test_backspace() ? "true" : "false");

 printf("stringutils.escape_string_test_tab ==> %s\n", stringutils__escape_string_test_tab() ? "true" : "false");

 printf("stringutils.escape_string_test_newline ==> %s\n", stringutils__escape_string_test_newline() ? "true" : "false");

 printf("stringutils.escape_string_test_formfeed ==> %s\n", stringutils__escape_string_test_formfeed() ? "true" : "false");

 printf("stringutils.escape_string_test_carriage_return ==> %s\n", stringutils__escape_string_test_carriage_return() ? "true" : "false");

 printf("stringutils.escape_string_test_mixed_string ==> %s\n", stringutils__escape_string_test_mixed_string() ? "true" : "false");

 printf("stringutils.escape_string_test_all_special_chars ==> %s\n", stringutils__escape_string_test_all_special_chars() ? "true" : "false");

 printf("stringutils.trim_str_test0 ==> %s\n", stringutils__trim_str_test0() ? "true" : "false");

 printf("stringutils.trim_str_test1 ==> %s\n", stringutils__trim_str_test1() ? "true" : "false");

 printf("stringutils.trim_str_test2 ==> %s\n", stringutils__trim_str_test2() ? "true" : "false");

 printf("stringutils.trim_str_test3 ==> %s\n", stringutils__trim_str_test3() ? "true" : "false");

 printf("stringutils.trim_str_test4 ==> %s\n", stringutils__trim_str_test4() ? "true" : "false");

 printf("stringutils.trim_str_test5 ==> %s\n", stringutils__trim_str_test5() ? "true" : "false");

 printf("stringutils.trim_str_test6 ==> %s\n", stringutils__trim_str_test6() ? "true" : "false");

 printf("stringutils.join_test0 ==> %s\n", stringutils__join_test0() ? "true" : "false");

 printf("stringutils.join_test1 ==> %s\n", stringutils__join_test1() ? "true" : "false");

 printf("stringutils.join_test2 ==> %s\n", stringutils__join_test2() ? "true" : "false");

 printf("stringutils.join_test3 ==> %s\n", stringutils__join_test3() ? "true" : "false");
}
