DEMO := sha256
TC_THEORY := SHA256
MAIN_THEORY := SHA256
NIST_SUITE_NAME := SHA-256 byte-oriented ShortMsg/LongMsg
NIST_ZIP_URL := https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/shs/shabytetestvectors.zip
NIST_ZIP_MEMBERS := shabytetestvectors/SHA256ShortMsg.rsp shabytetestvectors/SHA256LongMsg.rsp
NIST_VECTOR_FILES := SHA256ShortMsg.rsp SHA256LongMsg.rsp

include ../crypto-demo.mk
