DEMO := aes
TC_THEORY := Rijndael
MAIN_THEORY := Rijndael
NIST_SUITE_NAME := AES-128 ECB KAT
NIST_ZIP_URL := https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/KAT_AES.zip
NIST_ZIP_MEMBERS := ECBGFSbox128.rsp ECBKeySbox128.rsp ECBVarKey128.rsp ECBVarTxt128.rsp
NIST_VECTOR_FILES := $(NIST_ZIP_MEMBERS)

include ../crypto-demo.mk
