DEMO := hmac
TC_THEORY := HMAC
MAIN_THEORY := HMAC
NIST_SUITE_NAME := HMAC SHA-256
NIST_ZIP_URL := https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/mac/hmactestvectors.zip
NIST_ZIP_MEMBERS := HMAC.rsp
NIST_VECTOR_FILES := HMAC.rsp

include ../crypto-demo.mk
